import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wrapper from "./wrapper";
import { decrypt, validateSession } from "@/utils";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React FrontEnd",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies().get("session")?.value;
  const session = await decrypt(cookie);
  console.log("middleware session", session);

  // 5. Redirect to /login if the user is not authenticated
  // if (!session?.userId) {
  //   return false;
  // }

  // return true;
  // const userSession = await validateSession();
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/4f00a527b1.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={inter.className}>
        <Wrapper userSession={!!session?.userId}>{children}</Wrapper>
      </body>
    </html>
  );
}
