import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { decrypt, validateSession } from "@/utils";
import { cookies } from "next/headers";
import { privateRoutes, publicRoutes } from "@/routes";
import HeaderAndSideNavComponent from "./components/HeaderAndSideNav/HeaderAndSideNav";
import Footer from "./components/Footer/Footer";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "React FrontEnd",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 5. Redirect to /login if the user is not authenticated

  // return true;

  // const session = await validateSession();
  const routes = [...publicRoutes];

  // if (session) {
  //   routes.push(...privateRoutes);
  // }

  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/4f00a527b1.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={inter.className}>
        <Providers>
          <HeaderAndSideNavComponent session={false} />
          <main className="flex min-h-screen   p-24">{children}</main>
          {/* </GlobalContext.Provider> */}
          {/* </Wrapper> */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
